name: WorldBorder
version: '${project.version}'
main: com.thatsoulyguy.worldborder.WorldBorder
api-version: '1.20'

commands:
  spawnpig:
    description: Spawns the border pig
    aliases:
      - sp
      - cp