name: WorldBorder
version: '${project.version}'
main: com.thatsoulyguy.worldborder.WorldBorder
api-version: '1.20'

commands:
  bordersmp:
    description: Main command for all BorderSMP Plugin's functionality.
    aliases:
      - bsmp
      - bs